{"errorMessage": "3 validation errors for CustomAPIGatewayProxyEventModel\nresource\n  Field required [type=missing, input_value={'httpMethod': 'GET', 'pa...meters': {'limit': '5'}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing\nheaders\n  Field required [type=missing, input_value={'httpMethod': 'GET', 'pa...meters': {'limit': '5'}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing\nmultiValueHeaders\n  Field required [type=missing, input_value={'httpMethod': 'GET', 'pa...meters': {'limit': '5'}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing", "errorType": "ValidationError", "requestId": "b8b0537b-96c0-4a4b-a803-dee732216576", "stackTrace": ["  File \"/opt/python/aws_lambda_powertools/tracing/tracer.py\", line 351, in decorate\n    response = lambda_handler(event, context, **kwargs)\n", "  File \"/opt/python/aws_lambda_powertools/middleware_factory/factory.py\", line 140, in wrapper\n    response = middleware()\n", "  File \"/opt/python/aws_lambda_powertools/utilities/parser/parser.py\", line 114, in event_parser\n    parsed_event = parse(event=event, model=model, envelope=envelope)\n", "  File \"/opt/python/aws_lambda_powertools/utilities/parser/parser.py\", line 187, in parse\n    return envelope().parse(data=event, model=model)\n", "  File \"/opt/python/utils/envelopes.py\", line 29, in parse\n    event = CustomAPIGatewayProxyEventModel(**data)\n", "  File \"/opt/python/pydantic/main.py\", line 253, in __init__\n    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n"]}
